site:
  baseUrl: https://blog.cordx.cx
  title: Bibliotheca ex Machina
srcDir: src
outputDir: dist
templatesDir: templates

rules:
  - name: posts
    action:
      name: build
      template: post.html
    patterns:
      - posts//*.md
  - name: index
    action:
      name: build
      template: index.html
    patterns:
      - index.md
  - name: pages
    action:
      name: build
      template: base.html
    patterns:
      - //*.md
  - name: assets
    action:
      name: copy
    patterns:
      - //*
